### ISSUE TITLE
User Auth Review

### ISSUE THREAD

**Issue by jmeyer90** [Solomon-T/live_polls#2]
Tasks to be completed:

- Inputting invalid credentials on the sign in form cause the page to go blank.
- Better styling on the Navbar when shrinking the page width. Try setting a min-width property so things don't overlap or get pushed together.
- Demo user button does not work on the sign up or login page.

**Comment by Solomon-T** [comment]
Tasks completed 

- Inputting invalid credentials on the signup corrected
- Nav bar and whole page made responsive
- Demo user button functionality added on the sign up and login page.
